---
sudo: required
services:
  - docker
language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
script: bundle exec rake $RAKE_TASK
env:
  matrix:
  - RAKE_TASK=test
  - RAKE_TASK=beaker
